=== 1u0/demo/src/main/resources/providers/example.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "required": [
    "id",
    "doctor",
    "durationInMinutes",
    "time",
    "service",
    "location"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "string",
      "examples": [
        "b11e0ba5-53d1-4d58-8c51-5e3c15bfb560"
      ]
    },
    "doctor": {
      "$id": "#/properties/doctor",
      "type": "object",
      "title": "The Doctor Schema",
      "required": [
        "firstName",
        "lastName"
      ],
      "properties": {
        "firstName": {
          "$id": "#/properties/doctor/properties/firstName",
          "type": "string"
        },
        "lastName": {
          "$id": "#/properties/doctor/properties/lastName",
          "type": "string"
        }
      }
    },
    "durationInMinutes": {
      "$id": "#/properties/durationInMinutes",
      "type": "integer",
      "minimum": 0
    },
    "time": {
      "$id": "#/properties/time",
      "type": "string",
      "format": "date-time",
      "examples": [
        "2020-01-16 03:44:00"
      ]
    },
    "service": {
      "$id": "#/properties/service",
      "type": "object",
      "title": "The Service Schema",
      "required": [
        "name",
        "price"
      ],
      "properties": {
        "name": {
          "$id": "#/properties/service/properties/name",
          "type": "string",
          "examples": [
            "Counselling"
          ],
          "pattern": "^(.*)$"
        },
        "price": {
          "$id": "#/properties/service/properties/price",
          "type": "integer",
          "minimum": 0,
          "examples": [
            2672
          ]
        }
      }
    },
    "location": {
      "$id": "#/properties/location",
      "type": "object",
      "title": "The Location Schema",
      "required": [
        "name",
        "timeZoneCode"
      ],
      "properties": {
        "name": {
          "$id": "#/properties/location/properties/name",
          "type": "string",
          "examples": [
            "Kansas City Care"
          ],
          "pattern": "^(.*)$"
        },
        "timeZoneCode": {
          "$id": "#/properties/location/properties/timeZoneCode",
          "type": "string",
          "examples": [
            "America/Chicago"
          ],
          "pattern": "^(.*)$"
        }
      }
    }
  }
}

=== 1u0/demo/src/test/resources/samples/providers/example/sample1.json
[
  {
    "doctor": {
      "firstName": "Bret",
      "lastName": "Ortiz"
    },
    "durationInMinutes": 5,
    "time": "2020-01-16 03:44:00",
    "service": {
      "name": "Counselling",
      "price": 2672
    },
    "location": {
      "name": "Kansas City Care",
      "timeZoneCode": "America/Chicago"
    },
    "id": "b11e0ba5-53d1-4d58-8c51-5e3c15bfb560"
  },
  {
    "doctor": {
      "firstName": "Salvador",
      "lastName": "Flatley"
    },
    "durationInMinutes": 12,
    "time": "2020-01-16 09:47:00",
    "service": {
      "name": "Physiotherapy consultation",
      "price": 9832
    },
    "location": {
      "name": "Wichita rehabilitation center",
      "timeZoneCode": "America/Chicago"
    },
    "id": "0059a3a5-069e-4283-b150-4c5196273a29"
  },
  {
    "doctor": {
      "firstName": "Bret",
      "lastName": "Ortiz"
    },
    "durationInMinutes": 10,
    "time": "2020-01-16 03:44:00",
    "service": {
      "name": "X-Ray",
      "price": 8548
    },
    "location": {
      "name": "KC Doctors",
      "timeZoneCode": "America/Chicago"
    },
    "id": "8ec28eba-64ae-46ad-89bb-072daf06d7e2"
  }
]

=== 1u0/demo/src/test/resources/samples/providers/example/sample2.json
[
  {
    "doctor": {
      "firstName": "Betty",
      "lastName": "Mosciski"
    },
    "durationInMinutes": 14,
    "time": "2020-01-16 05:01:00",
    "service": {
      "name": "X-Ray",
      "price": 8548
    },
    "location": {
      "name": "Kansas City Medical Centre",
      "timeZoneCode": "America/Chicago"
    },
    "id": "8b5df407-b495-435a-8204-4e735f666888"
  },
  {
    "doctor": {
      "firstName": "Betty",
      "lastName": "Mosciski"
    },
    "durationInMinutes": 10,
    "time": "2020-01-16 05:01:00",
    "service": {
      "name": "Discolored butthole flaps inspection",
      "price": 3415
    },
    "location": {
      "name": "Kansas City Medical Centre",
      "timeZoneCode": "America/Chicago"
    },
    "id": "ffbeacbd-4196-459a-bb30-e45c274613ee"
  },
  {
    "doctor": {
      "firstName": "Betty",
      "lastName": "Mosciski"
    },
    "durationInMinutes": 9,
    "time": "2020-01-16 05:01:00",
    "service": {
      "name": "Physiotherapy consultation",
      "price": 9832
    },
    "location": {
      "name": "Kansas City Care",
      "timeZoneCode": "America/Chicago"
    },
    "id": "5c357963-f3fe-4541-86d5-b607be9739e9"
  },
  {
    "doctor": {
      "firstName": "Betty",
      "lastName": "Mosciski"
    },
    "durationInMinutes": 7,
    "time": "2020-01-16 05:01:00",
    "service": {
      "name": "Teeth cleaning",
      "price": 6815
    },
    "location": {
      "name": "Wichita rehabilitation center",
      "timeZoneCode": "America/Chicago"
    },
    "id": "90b41d63-c7a0-4e3c-9657-f6d1a6fd36ee"
  }
]
